// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicStreamerBackend.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MusicStreamerBackend.Migrations
{
    [DbContext(typeof(MusicStreamerDbContext))]
    [Migration("20260404202427_AddedPlaylistsTable")]
    partial class AddedPlaylistsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.Music.AlbumEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<string>("Genre")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.Music.ArtistEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.Music.ExtAlbumEF", b =>
                {
                    b.Property<string>("ExtId")
                        .HasColumnType("text");

                    b.Property<int>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ExtId");

                    b.HasIndex("AlbumId");

                    b.ToTable("ExtAlbums");
                });

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.Music.ExtArtistEF", b =>
                {
                    b.Property<string>("ExtId")
                        .HasColumnType("text");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ExtId");

                    b.HasIndex("ArtistId");

                    b.ToTable("ExtArtists");
                });

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.Music.TrackAltFormatsEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackAltFormats");
                });

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.Music.TrackEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.User.ListeningEventEF", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<int>("Context")
                        .HasColumnType("integer");

                    b.Property<float>("DurationMs")
                        .HasColumnType("real");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<float>("PositionMs")
                        .HasColumnType("real");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.HasIndex("TrackId");

                    b.ToTable("ListeningEvents");
                });

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.User.PlaylistEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PlaylistName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("TrackIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserPlaylists");
                });

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.Music.AlbumEF", b =>
                {
                    b.HasOne("MusicStreamerBackend.Data.EFModels.Music.ArtistEF", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.Music.ExtAlbumEF", b =>
                {
                    b.HasOne("MusicStreamerBackend.Data.EFModels.Music.AlbumEF", "Album")
                        .WithMany("ExtIds")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.Music.ExtArtistEF", b =>
                {
                    b.HasOne("MusicStreamerBackend.Data.EFModels.Music.ArtistEF", "Artist")
                        .WithMany("ExtIds")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.Music.TrackAltFormatsEF", b =>
                {
                    b.HasOne("MusicStreamerBackend.Data.EFModels.Music.TrackEF", "Track")
                        .WithMany("AltFormats")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.Music.TrackEF", b =>
                {
                    b.HasOne("MusicStreamerBackend.Data.EFModels.Music.AlbumEF", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicStreamerBackend.Data.EFModels.Music.ArtistEF", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.User.ListeningEventEF", b =>
                {
                    b.HasOne("MusicStreamerBackend.Data.EFModels.Music.TrackEF", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.Music.AlbumEF", b =>
                {
                    b.Navigation("ExtIds");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.Music.ArtistEF", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("ExtIds");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicStreamerBackend.Data.EFModels.Music.TrackEF", b =>
                {
                    b.Navigation("AltFormats");
                });
#pragma warning restore 612, 618
        }
    }
}
