"""replace genre columns with json

Revision ID: ab5abf6a02ee
Revises: bd8a01173a47
Create Date: 2026-03-30 23:18:32.892510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab5abf6a02ee'
down_revision: Union[str, Sequence[str], None] = 'bd8a01173a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_features', sa.Column('genres', postgresql.JSON(astext_type=sa.Text()), nullable=True), schema='recommender')
    op.drop_column('track_features', 'genre', schema='recommender')
    op.drop_column('track_features', 'subgenre', schema='recommender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_features', sa.Column('subgenre', sa.VARCHAR(), autoincrement=False, nullable=True), schema='recommender')
    op.add_column('track_features', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True), schema='recommender')
    op.drop_column('track_features', 'genres', schema='recommender')
    # ### end Alembic commands ###
