"""create track_features table

Revision ID: b7b9b3f29909
Revises: 
Create Date: 2026-03-30 22:25:19.521157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b7b9b3f29909'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dotnet_track_id', sa.Integer(), nullable=False),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('scale', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1280), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='recommender'
    )
    op.create_index(op.f('ix_recommender_track_features_dotnet_track_id'), 'track_features', ['dotnet_track_id'], unique=True, schema='recommender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommender_track_features_dotnet_track_id'), table_name='track_features', schema='recommender')
    op.drop_table('track_features', schema='recommender')
    # ### end Alembic commands ###
