"""add genre columns to track_features

Revision ID: bd8a01173a47
Revises: b7b9b3f29909
Create Date: 2026-03-30 22:53:39.807762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8a01173a47'
down_revision: Union[str, Sequence[str], None] = 'b7b9b3f29909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_features', sa.Column('genre', sa.String(), nullable=True), schema='recommender')
    op.add_column('track_features', sa.Column('subgenre', sa.String(), nullable=True), schema='recommender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_features', 'subgenre', schema='recommender')
    op.drop_column('track_features', 'genre', schema='recommender')
    # ### end Alembic commands ###
